import { createSlice, createAsyncThunk, PayloadAction } from '@reduxjs/toolkit';
import { Product } from '../../types';
import { cartsApi, CartItemRow, CartSessionRow, CartsResponse } from '../../services/api';
import { getCartLimit } from '../planLimits';
import { login, verifyRegistration, fetchProfile, updatePlan } from './authSlice';

interface CartItem {
  product: Product;
  quantity: number;
}

export interface Cart {
  cartId: string;
  items: CartItem[];
  customerName: string;
  customerId?: string;
  discount: number;
}

interface CartState {
  carts: Cart[];
  activeCartId: string;
  loading: boolean;
  maxCarts: number;
}

const guestCart = (): Cart => ({
  cartId: 'default',
  items: [],
  customerName: 'Walk-in',
  discount: 0,
});

const initialState: CartState = {
  carts: [guestCart()],
  activeCartId: 'default',
  loading: false,
  maxCarts: 4,
};

// Rebuild Redux carts from DB items + session metadata.
// Sessions are the source of truth for customer identity and discount —
// without them every cart resets to "Walk-in" with no profile on every reload.
function buildCartsFromRows(items: CartItemRow[], sessions: CartSessionRow[]): Cart[] {
  const sessionMeta = new Map<string, CartSessionRow>(sessions.map((s) => [s.id, s]));

  const itemsBySession = new Map<string, CartItem[]>();
  for (const row of items) {
    if (!row.product) continue;
    if (!itemsBySession.has(row.sessionId)) itemsBySession.set(row.sessionId, []);
    itemsBySession.get(row.sessionId)!.push({
      product: row.product as Product,
      quantity: row.qty,
    });
  }

  const allIds = new Set([...itemsBySession.keys(), ...sessionMeta.keys()]);

  const defaultMeta = sessionMeta.get('default');
  const result: Cart[] = [
    {
      cartId: 'default',
      items: itemsBySession.get('default') ?? [],
      customerName: defaultMeta?.customerName ?? 'Walk-in',
      customerId: defaultMeta?.customerId ?? undefined,
      discount: defaultMeta?.discount ?? 0,
    },
  ];

  for (const id of allIds) {
    if (id === 'default') continue;
    const meta = sessionMeta.get(id);
    result.push({
      cartId: id,
      items: itemsBySession.get(id) ?? [],
      customerName: meta?.customerName ?? 'Walk-in',
      customerId: meta?.customerId ?? undefined,
      discount: meta?.discount ?? 0,
    });
  }

  return result;
}

// ── Customer identity helpers (localStorage layer) ───────────────────────────
//
// The DB-backed cart_sessions table is the authoritative store, but it requires
// the NestJS server to have loaded the regenerated Prisma client.  localStorage
// acts as an immediately-available fallback that covers the gap and makes the
// feature work for existing carts that have no session row.
//
// Keys: "shopiq_cart_customer_{cartId}"
// Values: JSON { customerName: string; customerId: string | undefined }

const CUSTOMER_KEY = (cartId: string) => `shopiq_cart_customer_${cartId}`;

function saveCustomerLocally(cartId: string, customerName: string, customerId?: string) {
  try {
    localStorage.setItem(CUSTOMER_KEY(cartId), JSON.stringify({ customerName, customerId }));
  } catch { /* private-browsing — ignore */ }
}

function loadCustomerLocally(cartId: string): { customerName: string; customerId?: string } | null {
  try {
    const raw = localStorage.getItem(CUSTOMER_KEY(cartId));
    return raw ? JSON.parse(raw) : null;
  } catch { return null; }
}

function removeCustomerLocally(cartId: string) {
  try { localStorage.removeItem(CUSTOMER_KEY(cartId)); } catch { /* ignore */ }
}

// ── Async thunks ──────────────────────────────────────────────────────────────

export const fetchCarts = createAsyncThunk('cart/fetchAll', async () => {
  return await cartsApi.getAll();
});

// Create a new cart tab and immediately persist session metadata to MySQL.
// cartId is generated by the caller so action.meta.arg carries it,
// letting the `pending` handler add the cart to Redux state right away
// (optimistic update) — UI and toast are in sync with no API wait.
export const createCartWithSession = createAsyncThunk(
  'cart/createWithSession',
  async (
    payload: { cartId: string; customerName: string; customerId?: string },
    { rejectWithValue }
  ) => {
    try {
      await cartsApi.saveSession(payload.cartId, {
        customerName: payload.customerName,
        customerId: payload.customerId,
        discount: 0,
      });
      return payload;
    } catch (err: any) {
      return rejectWithValue(err.message ?? 'Failed to create cart');
    }
  }
);

export const addItemToCart = createAsyncThunk(
  'cart/addItem',
  async (
    { product, sessionId }: { product: Product; sessionId: string },
    { rejectWithValue }
  ) => {
    try {
      return await cartsApi.addItem({
        productId: product.id,
        qty: 1,
        price: product.sellPrice,
        sessionId,
      });
    } catch (err: any) {
      return rejectWithValue(err.message ?? 'Failed to add item to cart');
    }
  }
);

export const setItemQtyInCart = createAsyncThunk(
  'cart/setQty',
  async (
    { productId, qty, sessionId }: { productId: string; qty: number; sessionId: string },
    { rejectWithValue }
  ) => {
    try {
      if (qty <= 0) {
        await cartsApi.removeItem(productId, sessionId);
        return null;
      }
      return await cartsApi.setQty(productId, qty, sessionId);
    } catch (err: any) {
      return rejectWithValue(err.message ?? 'Failed to update quantity');
    }
  }
);

export const removeItemFromCart = createAsyncThunk(
  'cart/removeItem',
  async (
    { productId, sessionId }: { productId: string; sessionId: string },
    { rejectWithValue }
  ) => {
    try {
      await cartsApi.removeItem(productId, sessionId);
      return { productId, sessionId };
    } catch (err: any) {
      return rejectWithValue(err.message ?? 'Failed to remove item');
    }
  }
);

export const clearCartSession = createAsyncThunk(
  'cart/clearSession',
  async (sessionId: string, { rejectWithValue }) => {
    try {
      await cartsApi.clearSession(sessionId);
      return sessionId;
    } catch (err: any) {
      return rejectWithValue(err.message ?? 'Failed to clear cart');
    }
  }
);

// ── Slice ─────────────────────────────────────────────────────────────────────

const cartSlice = createSlice({
  name: 'cart',
  initialState,
  reducers: {
    setMaxCarts(state, action: PayloadAction<number>) {
      state.maxCarts = action.payload;
    },
    switchCart(state, action: PayloadAction<string>) {
      if (state.carts.find((c) => c.cartId === action.payload)) {
        state.activeCartId = action.payload;
      }
    },
    setDiscount(state, action: PayloadAction<number>) {
      const cart = state.carts.find((c) => c.cartId === state.activeCartId);
      if (cart) cart.discount = action.payload;
    },
  },
  extraReducers: (builder) => {
    builder

      // ── fetchCarts: rebuild state from MySQL ───────────────────────
      .addCase(fetchCarts.pending, (state) => {
        state.loading = true;
      })
      .addCase(fetchCarts.fulfilled, (state, action) => {
        state.loading = false;
        const { items = [], sessions = [] } = (action.payload as CartsResponse) ?? {};
        const fromDb = buildCartsFromRows(items, sessions);
        const dbIds = new Set(fromDb.map((c) => c.cartId));

        // Preserve any cart already in Redux that the DB hasn't acknowledged yet.
        const inFlightCarts = state.carts.filter((c) => !dbIds.has(c.cartId));

        state.carts = [...fromDb, ...inFlightCarts];

        // Apply localStorage customer data as a fallback for carts whose session
        // row is missing from the DB (e.g. the backend hasn't been restarted yet
        // after prisma generate, or the session write failed silently).
        for (const cart of state.carts) {
          if (!cart.customerId) {
            const local = loadCustomerLocally(cart.cartId);
            if (local?.customerId) {
              cart.customerName = local.customerName;
              cart.customerId   = local.customerId;
            }
          }
        }

        if (!state.carts.find((c) => c.cartId === state.activeCartId)) {
          state.activeCartId = 'default';
        }
      })
      .addCase(fetchCarts.rejected, (state) => {
        state.loading = false;
      })

      // ── createCartWithSession ──────────────────────────────────────
      // pending  → optimistic: add cart instantly; write customer info to localStorage
      // fulfilled → no-op: already in state from pending
      // rejected  → revert: remove the cart and clear localStorage entry
      .addCase(createCartWithSession.pending, (state, action) => {
        if (state.carts.length >= state.maxCarts) return;
        const { cartId, customerName, customerId } = action.meta.arg;
        state.carts.push({ cartId, items: [], customerName, customerId, discount: 0 });
        state.activeCartId = cartId;
        // Write customer identity to localStorage immediately so it survives a
        // reload even if the DB session write is still in-flight or fails.
        if (customerId) saveCustomerLocally(cartId, customerName, customerId);
      })
      .addCase(createCartWithSession.rejected, (state, action) => {
        const { cartId } = action.meta.arg;
        state.carts = state.carts.filter((c) => c.cartId !== cartId);
        if (state.activeCartId === cartId) {
          state.activeCartId = state.carts[0]?.cartId ?? 'default';
        }
        removeCustomerLocally(cartId);
      })

      // ── addItemToCart: optimistic add → revert on failure ──────────
      .addCase(addItemToCart.pending, (state, action) => {
        const { product, sessionId } = action.meta.arg;
        const cart = state.carts.find((c) => c.cartId === sessionId);
        if (!cart) return;
        const existing = cart.items.find((i) => i.product.id === product.id);
        if (existing) {
          if (existing.quantity < existing.product.stock) existing.quantity += 1;
        } else {
          cart.items.push({ product, quantity: 1 });
        }
      })
      .addCase(addItemToCart.rejected, (state, action) => {
        const { product, sessionId } = action.meta.arg;
        const cart = state.carts.find((c) => c.cartId === sessionId);
        if (!cart) return;
        const idx = cart.items.findIndex((i) => i.product.id === product.id);
        if (idx !== -1) {
          if (cart.items[idx].quantity > 1) cart.items[idx].quantity -= 1;
          else cart.items.splice(idx, 1);
        }
      })

      // ── setItemQtyInCart: optimistic update ────────────────────────
      .addCase(setItemQtyInCart.pending, (state, action) => {
        const { productId, qty, sessionId } = action.meta.arg;
        const cart = state.carts.find((c) => c.cartId === sessionId);
        if (!cart) return;
        if (qty <= 0) {
          cart.items = cart.items.filter((i) => i.product.id !== productId);
        } else {
          const item = cart.items.find((i) => i.product.id === productId);
          if (item) item.quantity = Math.min(qty, item.product.stock);
        }
      })

      // ── removeItemFromCart: optimistic remove ──────────────────────
      .addCase(removeItemFromCart.pending, (state, action) => {
        const { productId, sessionId } = action.meta.arg;
        const cart = state.carts.find((c) => c.cartId === sessionId);
        if (cart) cart.items = cart.items.filter((i) => i.product.id !== productId);
      })

      // ── clearCartSession: optimistic clear ────────────────────────
      .addCase(clearCartSession.pending, (state, action) => {
        const sessionId = action.meta.arg;
        removeCustomerLocally(sessionId);
        if (sessionId === 'default') {
          const cart = state.carts.find((c) => c.cartId === 'default');
          if (cart) {
            cart.items = [];
            cart.customerName = 'Walk-in';
            cart.customerId = undefined;
            cart.discount = 0;
          }
        } else {
          state.carts = state.carts.filter((c) => c.cartId !== sessionId);
          if (state.activeCartId === sessionId) {
            state.activeCartId = state.carts[0]?.cartId ?? 'default';
          }
        }
      })

      // ── plan limit sync from auth events ──────────────────────────
      .addCase(login.fulfilled, (state, action) => {
        state.maxCarts = getCartLimit(action.payload?.plan);
      })
      .addCase(verifyRegistration.fulfilled, (state, action) => {
        state.maxCarts = getCartLimit(action.payload?.plan);
      })
      .addCase(fetchProfile.fulfilled, (state, action) => {
        state.maxCarts = getCartLimit(action.payload?.plan);
      })
      .addCase(updatePlan, (state, action) => {
        state.maxCarts = getCartLimit(action.payload);
      });
  },
});

export const { setMaxCarts, switchCart, setDiscount } = cartSlice.actions;
export default cartSlice.reducer;
